#!/usr/bin/env python3

# imports
from nrpypn.eval_p_t_and_p_r import eval__P_t__and__P_r as evalPtPr
from string import Template
from math import sqrt
import numpy as np
import argparse
import os

def main():
    # parse arguments
    parser = argparse.ArgumentParser(description="Generates dyonic merger parameter file from template")

    parser.add_argument("-t",   "--template",           required=True, type=str,   help="Path to template parfile")
    parser.add_argument("-o",   "--output",             required=True, type=str,   help="Path to output parfile")
    parser.add_argument("-d",   "--distance",           required=True, type=float, help="Distance between punctures")
    parser.add_argument("-m",   "--mass_ratio",         required=True, type=float, help="Mass ratio")
    parser.add_argument("-tp",  "--charge_ratio_plus",  required=True, type=float, help="Charge to mass ratio of the 'plus' BH")
    parser.add_argument("-tm",  "--charge_ratio_minus", required=True, type=float, help="Charge to mass ratio of the 'minus' BH")
    parser.add_argument("-am",  "--alpha_minus",        required=True, type=float, help="E.M. rotation angle for 'minus' BH")
    parser.add_argument("-amt", "--alpha_minus_text",   required=True, type=str,   help="Text for alpha_minus in `out_dir`")

    args = parser.parse_args()

    template           = os.path.abspath(args.template)
    output             = os.path.abspath(args.output)
    distance           = args.distance
    mass_ratio         = args.mass_ratio
    charge_ratio_plus  = args.charge_ratio_plus
    charge_ratio_minus = args.charge_ratio_minus
    alpha_minus        = args.alpha_minus
    alpha_minus_text   = args.alpha_minus_text

    # open template parfile as a Python string template
    with open(template) as f:
        strtemplate = Template(f.read())

    # get template filename
    name = template.split("/")[-1]
    name = name[:-5]

    # nrpypn assumes that the mass ratio is larger than one for its computations
    if mass_ratio < 1:
        mass_ratio = 1/mass_ratio

    m_plus     = 1
    m_minus    = mass_ratio
    total_mass = m_minus + m_plus

    # total electric and magnetic charges
    q_plus  = charge_ratio_plus  * m_plus
    q_minus = charge_ratio_minus * m_minus

    # compute linear momentum for a quasi-circular inspiral with zero spin
    Pt, Pr = evalPtPr(mass_ratio, distance, 0, 0, 0, 0, 0, 0)

    factor = sqrt(1 - charge_ratio_plus * charge_ratio_minus)  # correction due to charges
    Pt = Pt * total_mass * factor
    Pr = Pr * total_mass * factor

    Px_plus,  Py_plus,  Pz_plus  = (-Pr, Pt, 0)
    Px_minus, Py_minus, Pz_minus = (Pr, -Pt, 0)

    # compute distances
    par_b = distance / 2

    x_plus  =   distance * m_minus / total_mass
    x_minus = - distance * m_plus  / total_mass

    center_offset = x_plus - par_b

    # compute size of AH
    rah_plus  = np.sqrt(m_plus**2  - q_plus**2)  / 2
    rah_minus = np.sqrt(m_minus**2 - q_minus**2) / 2

    # to avoid having the grid point on the puncture, we offset the mesh refinement to the nearest integer
    x_plus_int  = int(x_plus)
    x_minus_int = int(x_minus)

    # define output directory for the simulation
    out_dir = f"{name.capitalize()}_M={m_plus},{m_minus}-T={q_plus},{q_minus}-alpha=0,{alpha_minus_text}-x0={int(par_b)}_h=3"

    # output to parfile
    template_out = strtemplate.substitute(**locals())
    with open(output, "w") as f:
        f.write(template_out)

if __name__ == "__main__":
    main()
